version: "2.38.2"
services:
    
    #Database Server
    database:
       image: mysql:8.0
       ports:
         - 3306:3306 # internally/local:externally
       environment:
         - MYSQL_DATABASE=${DB_DATABASE}
         - MYSQL_USER=${DB_USERNAME}
         - MYSQL_PASSWORD=${DB_PASSWORD}
         - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
       volumes:
         - db-data:/var/lib/mysql

    # phpmyadmin:
    #     image: phpmyadmin
    #     ports:
    #       - '8080:80'
    #     environment:
    #     #  - MYSQL_DATABASE=${DB_DATABASE}
    #      - MYSQL_USER=${DB_USERNAME}
    #      - MYSQL_PASSWORD=${DB_PASSWORD}
    #      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    #     # volumes:
        #   db-data:  

volumes:
   db-data: ~ 